apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/compose: metrics
    app.kubernetes.io/part-of: odf-lvm-provisioner
  name: lvm-node-metrics
spec:
  ports:
  - name: lvm-metrics
    port: 23532
    protocol: TCP
    targetPort: 23532
  selector:
    exporter: lvm-operator
status:
  loadBalancer: {}
